export const STYLES = {
  georgian: {
    id: "georgian",
    name: "Georgian",
    origin: "Great Britain",
    period: "1714–1830",
    summary:
      "A palazzo in miniature: five-bay brick, piano of sash lights, and a pedimented doorcase of the Tuscan order.",
    wall: "brick",
    base: "ashlar",
    roofTex: "slate",
    roof: "hip",
    window: "sash",
    door: "classical",
    column: "doric",
    massing: "rect",
    symmetry: true,
    quoins: true,
    dentils: true,
    rusticatedBase: true,
    shutters: false,
    balcony: "none",
    stringCourse: true,
    cornice: true,
    chimney: "pair",
    porch: false,
    timber: false,
    bayWidth: 2.55,
    bayDepth: 2.5,
    baseHeight: 3.55,
    typicalHeight: 3.25,
    atticHeight: 2.9,
    pianoNobile: false,
    windowSill: 0.9,
    windowWidth: 1.12,
    windowHeight: 1.72,
    reveal: 0.14,
    defaults: { floors: 3, baysX: 5, baysZ: 3, columns: true, balconies: false, dormers: true },
    colors: {
      wall: ["#8a4034", "#7c382e", "#94483c"],
      mortar: "#d5ccbc",
      base: "#d2c6b2",
      trim: "#f1ece1",
      roof: "#3a3e48",
      door: "#1a1d22",
      frame: "#f1ece1",
      column: "#f4f0e6",
      interior: "#d9c7a6",
      wood: "#4a2f22",
      accent: "#f1ece1",
    },
  },
  victorian: {
    id: "victorian",
    name: "Victorian",
    origin: "England & the Atlantic",
    period: "1840–1900",
    summary:
      "Queen Anne picturesqueness: a projecting bay, wrap porch, steep gable and a chimney that refuses to be modest.",
    wall: "clapboard",
    wallAlt: "fish",
    base: "brick",
    roofTex: "shingle",
    roof: "gable",
    window: "sash2",
    door: "victorian",
    column: "craftsman",
    massing: "bay",
    symmetry: false,
    quoins: false,
    dentils: false,
    rusticatedBase: true,
    shutters: true,
    balcony: "none",
    stringCourse: false,
    cornice: true,
    chimney: "tall",
    porch: true,
    timber: false,
    bayWidth: 2.45,
    bayDepth: 2.4,
    baseHeight: 3.4,
    typicalHeight: 3.1,
    atticHeight: 2.8,
    pianoNobile: false,
    windowSill: 0.82,
    windowWidth: 1.05,
    windowHeight: 1.65,
    reveal: 0.1,
    defaults: { floors: 3, baysX: 4, baysZ: 3, columns: true, balconies: false, dormers: true },
    colors: {
      wall: ["#c4b48a", "#9aa584", "#c9a07a"],
      mortar: "#cfc6b6",
      base: "#7a3e32",
      trim: "#2f3a30",
      roof: "#4a3a32",
      door: "#6b2a24",
      frame: "#f3efe4",
      column: "#f3efe4",
      interior: "#e6d3b0",
      wood: "#5a3824",
      accent: "#6b8f71",
      timber: "#2a241c",
    },
  },
  haussmann: {
    id: "haussmann",
    name: "Haussmann",
    origin: "Paris",
    period: "1853–1870",
    summary:
      "Lutetian limestone, a rusticated base, wrought-iron gardes-corps and a zinc mansard pricked with dormers.",
    wall: "ashlar",
    base: "ashlar",
    roofTex: "zinc",
    roof: "mansard",
    window: "french",
    door: "carriage",
    column: "ionic",
    massing: "rect",
    symmetry: true,
    quoins: false,
    dentils: true,
    rusticatedBase: true,
    shutters: false,
    balcony: "haussmann",
    stringCourse: true,
    cornice: true,
    chimney: "pair",
    porch: false,
    timber: false,
    bayWidth: 2.7,
    bayDepth: 2.6,
    baseHeight: 4.1,
    typicalHeight: 3.35,
    atticHeight: 3.1,
    pianoNobile: true,
    windowSill: 0.7,
    windowWidth: 1.2,
    windowHeight: 2.05,
    reveal: 0.16,
    defaults: { floors: 6, baysX: 5, baysZ: 3, columns: false, balconies: true, dormers: true },
    colors: {
      wall: ["#d7cbb6", "#cfc1a8", "#e0d3bc"],
      mortar: "#b9ad98",
      base: "#c4b59a",
      trim: "#efe6d6",
      roof: "#6d7174",
      door: "#2a2420",
      frame: "#f4efe4",
      column: "#efe6d6",
      interior: "#e8d7b8",
      wood: "#4d3728",
      accent: "#1a1b1e",
    },
  },
  mediterranean: {
    id: "mediterranean",
    name: "Mediterranean",
    origin: "Iberia & the Maghreb",
    period: "1915–1935",
    summary:
      "Stucco, terracotta, and the cool shade of an arched loggia — a coastal villa with iron Juliets and deep eaves.",
    wall: "stucco",
    base: "ashlar",
    roofTex: "terracotta",
    roof: "hip",
    window: "arched",
    door: "arched",
    column: "tuscan",
    massing: "wing",
    symmetry: false,
    quoins: false,
    dentils: false,
    rusticatedBase: true,
    shutters: true,
    balcony: "iron",
    stringCourse: false,
    cornice: false,
    chimney: "one",
    porch: true,
    timber: false,
    bayWidth: 2.6,
    bayDepth: 2.55,
    baseHeight: 3.5,
    typicalHeight: 3.15,
    atticHeight: 2.85,
    pianoNobile: false,
    windowSill: 0.85,
    windowWidth: 1.1,
    windowHeight: 1.7,
    reveal: 0.18,
    defaults: { floors: 2, baysX: 5, baysZ: 3, columns: true, balconies: true, dormers: false },
    colors: {
      wall: ["#efe4d0", "#e6d3b4", "#f2e6d4"],
      mortar: "#d9cbb4",
      base: "#c2b49a",
      trim: "#f7f1e6",
      roof: "#c45a32",
      door: "#6b3a22",
      frame: "#5c4330",
      column: "#f4ead8",
      interior: "#f0e0c4",
      wood: "#5c3a24",
      accent: "#3d6a62",
    },
  },
  modernist: {
    id: "modernist",
    name: "Modernist",
    origin: "Europe",
    period: "1925–1965",
    summary:
      "White volumes, ribbon windows, a hovering slab — the five points of architecture reduced to a house.",
    wall: "stucco",
    base: "concrete",
    roofTex: "concrete",
    roof: "flat",
    window: "ribbon",
    door: "slab",
    column: "pilotis",
    massing: "offset",
    symmetry: false,
    quoins: false,
    dentils: false,
    rusticatedBase: false,
    shutters: false,
    balcony: "modern",
    stringCourse: false,
    cornice: false,
    chimney: "none",
    porch: false,
    timber: false,
    bayWidth: 2.8,
    bayDepth: 2.7,
    baseHeight: 3.3,
    typicalHeight: 3.1,
    atticHeight: 3.0,
    pianoNobile: false,
    windowSill: 1.05,
    windowWidth: 2.1,
    windowHeight: 1.35,
    reveal: 0.08,
    defaults: { floors: 3, baysX: 4, baysZ: 3, columns: true, balconies: true, dormers: false },
    colors: {
      wall: ["#f3f1ea", "#eceae2", "#f7f6f1"],
      mortar: "#ddd",
      base: "#b4ada2",
      trim: "#f7f7f4",
      roof: "#b0aaa0",
      door: "#1c1c1c",
      frame: "#1a1a1a",
      column: "#f4f2ec",
      interior: "#d8d2c6",
      wood: "#8a6a4a",
      accent: "#b43c2a",
    },
  },
  tudor: {
    id: "tudor",
    name: "Tudor",
    origin: "England",
    period: "1485–1603 / Revival",
    summary:
      "Steep gables, black timber on limewash, a clustered stack — the manor house as a romantic silhouette.",
    wall: "stucco",
    base: "brick",
    roofTex: "slate",
    roof: "steep-gable",
    window: "casement",
    door: "board",
    column: "timber",
    massing: "gable-front",
    symmetry: false,
    quoins: false,
    dentils: false,
    rusticatedBase: true,
    shutters: false,
    balcony: "none",
    stringCourse: false,
    cornice: false,
    chimney: "cluster",
    porch: false,
    timber: true,
    bayWidth: 2.5,
    bayDepth: 2.45,
    baseHeight: 3.3,
    typicalHeight: 3.05,
    atticHeight: 2.7,
    pianoNobile: false,
    windowSill: 0.9,
    windowWidth: 0.7,
    windowHeight: 1.45,
    reveal: 0.12,
    defaults: { floors: 2, baysX: 5, baysZ: 3, columns: false, balconies: false, dormers: true },
    colors: {
      wall: ["#efe6d2", "#e8dcc4", "#f3ead8"],
      mortar: "#cfc4b0",
      base: "#8b4034",
      trim: "#2c2118",
      roof: "#3a3d44",
      door: "#2a1c14",
      frame: "#2c2118",
      column: "#2c2118",
      interior: "#e2d0ae",
      wood: "#3a2818",
      accent: "#8b4034",
      timber: "#241910",
    },
  },
  deco: {
    id: "deco",
    name: "Art Deco",
    origin: "Paris / New York",
    period: "1925–1940",
    summary:
      "Vertical fins, set-back massing, chevron ornament and metal windows — a residence with skyscraper manners.",
    wall: "ashlar",
    base: "ashlar",
    roofTex: "zinc",
    roof: "flat",
    window: "metal",
    door: "deco",
    column: "deco",
    massing: "setback",
    symmetry: true,
    quoins: false,
    dentils: false,
    rusticatedBase: true,
    shutters: false,
    balcony: "none",
    stringCourse: true,
    cornice: false,
    chimney: "none",
    porch: false,
    timber: false,
    bayWidth: 2.5,
    bayDepth: 2.5,
    baseHeight: 3.7,
    typicalHeight: 3.2,
    atticHeight: 3.05,
    pianoNobile: false,
    windowSill: 0.85,
    windowWidth: 1.15,
    windowHeight: 1.8,
    reveal: 0.12,
    defaults: { floors: 5, baysX: 5, baysZ: 3, columns: true, balconies: false, dormers: false },
    colors: {
      wall: ["#cbbba4", "#d4c4aa", "#c0b094"],
      mortar: "#a89880",
      base: "#2a2c30",
      trim: "#d8c8a8",
      roof: "#5c6064",
      door: "#1a1a1c",
      frame: "#2a2c30",
      column: "#d8c8a8",
      interior: "#dcc8a4",
      wood: "#3a2a1c",
      accent: "#b8943e",
    },
  },
  brutalist: {
    id: "brutalist",
    name: "Brutalist",
    origin: "Britain & Japan",
    period: "1955–1975",
    summary:
      "Béton brut, deep reveals, hovering slabs — a house of weight, shadow, and honest formwork.",
    wall: "concrete",
    base: "concrete",
    roofTex: "concrete",
    roof: "flat",
    window: "deep",
    door: "brutal",
    column: "pier",
    massing: "chunk",
    symmetry: false,
    quoins: false,
    dentils: false,
    rusticatedBase: false,
    shutters: false,
    balcony: "chunk",
    stringCourse: false,
    cornice: false,
    chimney: "none",
    porch: false,
    timber: false,
    bayWidth: 2.9,
    bayDepth: 2.8,
    baseHeight: 3.4,
    typicalHeight: 3.2,
    atticHeight: 3.1,
    pianoNobile: false,
    windowSill: 1.0,
    windowWidth: 1.35,
    windowHeight: 1.5,
    reveal: 0.42,
    defaults: { floors: 4, baysX: 4, baysZ: 3, columns: true, balconies: true, dormers: false },
    colors: {
      wall: ["#9a958c", "#8e8980", "#a39e94"],
      mortar: "#7a756c",
      base: "#8a8580",
      trim: "#b0aaa2",
      roof: "#8c877e",
      door: "#2c2c2c",
      frame: "#3a3a38",
      column: "#9a958c",
      interior: "#c2b8a8",
      wood: "#5a4a3a",
      accent: "#4a4e52",
    },
  },
};

export const STYLE_LIST = Object.values(STYLES);
