"use strict";
/* ==========================================================================
   obj_to_meshdata.js -- convert the engine's reference Suzanne OBJ into the
   prototype's js/mesh-data.js format, PRESERVING original polygon topology:
   quads stay quads, ngons stay ngons, tris stay tris (no fan-triangulation).
   MESH_FACES is a jagged array of vertex loops. Normals are recomputed as
   area-weighted smooth per-vertex normals (accumulated over each polygon's fan
   triangles, so ngons are weighted correctly). The OBJ's own vn are per-corner
   and don't map 1:1 onto the shared vertex array, so we rebuild them.
     node tools/obj_to_meshdata.js
   ========================================================================== */
const fs = require("fs");
const path = require("path");

const OBJ = "C:/Users/OS/Documents/Frontier/Engine/EngineContent/ReferenceGeometry/Suzzane.obj";
const OUT = path.join(__dirname, "..", "js", "mesh-data.js");

const src = fs.readFileSync(OBJ, "utf8").split(/\r?\n/);
const verts = [];   // [x,y,z]
const polys = [];   // [ [v0,v1,v2,(v3...)], ... ] (0-based) -- original loops

for (const line of src) {
  if (line.startsWith("v ")) {
    const p = line.split(/\s+/).slice(1).map(Number);
    verts.push([p[0], p[1], p[2]]);
  } else if (line.startsWith("f ")) {
    // each token is v/vt/vn (1-based); we only need the v index. Keep the loop.
    const loop = line.split(/\s+/).slice(1).map(t => parseInt(t.split("/")[0], 10) - 1);
    if (loop.length >= 3) polys.push(loop);
  }
}

const vertCount = verts.length;
const positions = new Array(vertCount * 3);
for (let v = 0; v < vertCount; v++) {
  positions[v * 3] = verts[v][0];
  positions[v * 3 + 1] = verts[v][1];
  positions[v * 3 + 2] = verts[v][2];
}

// area-weighted smooth normals: fan-triangulate each polygon only to accumulate
// each fan triangle's face normal (magnitude ~ 2*area) onto its verts, then
// normalise. The fan is a normals-only detail here; MESH_FACES stays polygons.
const normals = new Array(vertCount * 3).fill(0);
for (const loop of polys) {
  for (let i = 1; i + 1 < loop.length; i++) {
    const a = loop[0], b = loop[i], c = loop[i + 1];
    const ax = verts[a][0], ay = verts[a][1], az = verts[a][2];
    const e1x = verts[b][0] - ax, e1y = verts[b][1] - ay, e1z = verts[b][2] - az;
    const e2x = verts[c][0] - ax, e2y = verts[c][1] - ay, e2z = verts[c][2] - az;
    const nx = e1y * e2z - e1z * e2y;
    const ny = e1z * e2x - e1x * e2z;
    const nz = e1x * e2y - e1y * e2x;
    for (const v of [a, b, c]) { normals[v * 3] += nx; normals[v * 3 + 1] += ny; normals[v * 3 + 2] += nz; }
  }
}
for (let v = 0; v < vertCount; v++) {
  const x = normals[v * 3], y = normals[v * 3 + 1], z = normals[v * 3 + 2];
  const l = Math.hypot(x, y, z) || 1;
  normals[v * 3] = x / l; normals[v * 3 + 1] = y / l; normals[v * 3 + 2] = z / l;
}

const faceCount = polys.length;
// arity histogram for the generation log (e.g. { 3: 32, 4: 468 })
const arity = {};
for (const loop of polys) arity[loop.length] = (arity[loop.length] || 0) + 1;

const round = n => Math.round(n * 1e5) / 1e5;
const arr = a => "[" + a.map(round).join(",") + "]";
// jagged faces: one inner array per polygon loop
const facesLit = "[" + polys.map(loop => "[" + loop.join(",") + "]").join(",") + "]";

const out =
`"use strict";
/* ==========================================================================
   mesh-data.js  --  GENERATED by tools/obj_to_meshdata.js, do not hand-edit.
   Blender Suzanne (engine ReferenceGeometry/Suzzane.obj), ORIGINAL polygons
   preserved -- quads stay quads, ngons stay ngons, tris stay tris.
   POSITIONS: flat xyz (${vertCount} verts).  NORMALS: flat xyz (smooth).
   FACES: jagged array of vertex loops (${faceCount} polygons; arity ${JSON.stringify(arity)}).
   ========================================================================== */
const MESH_POSITIONS = ${arr(positions)};
const MESH_NORMALS = ${arr(normals)};
const MESH_FACES = ${facesLit};
const MESH = { positions: MESH_POSITIONS, normals: MESH_NORMALS, faces: MESH_FACES,
               vertCount: ${vertCount}, faceCount: ${faceCount} };
`;

fs.writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${vertCount} verts, ${faceCount} polygons, arity ${JSON.stringify(arity)}`);
